In [89]:
import pandas as pd
import requests

requisicao = requests.get("https://pt.wikipedia.org/wiki/Campeonato_Brasileiro_de_Futebol_de_2023_-_S%C3%A9rie_A")

tabelas = pd.read_html(requisicao.text)
tabela_classificacao = tabelas[6]
tabela_jogos = tabelas[7]
display(tabela_classificacao)
display(tabela_jogos)

,Pos,Equipevde,Pts,J,V,E,D,GP,GC,SG,Classificação ou descenso
0,1,Palmeiras (X),62,34,18,8,8,56,30,+26,Fase de grupos da Copa Libertadores de 2024
1,2,Botafogo (X),60,33,18,6,9,53,30,+23,Fase de grupos da Copa Libertadores de 2024
2,3,Grêmio (X),59,34,18,5,11,57,50,+7,Fase de grupos da Copa Libertadores de 2024
3,4,Red Bull Bragantino (X),59,33,16,11,6,46,29,+17,Fase de grupos da Copa Libertadores de 2024
4,5,Atlético Mineiro (X),57,34,16,9,9,43,27,+16,Segunda fase da Copa Libertadores de 2024
5,6,Flamengo (X),57,33,16,9,8,50,37,+13,Segunda fase da Copa Libertadores de 2024
6,7,Athletico Paranaense,51,34,13,12,9,47,39,+8,Fase de grupos da Copa Sul-Americana de 2024
7,8,Fluminense (Q),47,33,13,8,12,43,42,+1,Fase de grupos da Copa Libertadores de 2024[a]
8,9,Cuiabá,47,34,13,8,13,36,35,+1,Fase de grupos da Copa Sul-Americana de 2024
9,10,São Paulo (Q),46,33,12,10,11,37,35,+2,Fase de grupos da Copa Libertadores de 2024[b]
10,11,Corinthians,44,34,10,14,10,39,39,0,Fase de grupos da Copa Sul-Americana de 2024
11,12,Fortaleza,43,33,12,7,14,36,38,−2,Fase de grupos da Copa Sul-Americana de 2024
12,13,Internacional,43,34,11,10,13,38,43,−5,Fase de grupos da Copa Sul-Americana de 2024
13,14,Santos,42,34,11,9,14,37,55,−18,Fase de grupos da Copa Sul-Americana de 2024
14,15,Vasco da Gama,40,33,11,7,15,35,43,−8,NaN
15,16,Cruzeiro,40,33,10,10,13,30,28,+2,NaN
16,17,Bahia,38,34,10,8,16,39,47,−8,Rebaixados à Série B de 2024
17,18,Goiás,35,34,8,11,15,34,49,−15,Rebaixados à Série B de 2024
18,19,Coritiba,29,34,8,5,21,39,67,−28,Rebaixados à Série B de 2024
19,20,América Mineiro (R),21,34,4,9,21,39,71,−32,Rebaixados à Série B de 2024

,Casa \ Fora,AMM,ATP,ATM,BAH,BOT,COR,CTB,CRU,CUI,...,FLU,FOR,GOI,GRE,INT,PAL,RBB,SAN,SPA,VAS
0,América Mineiro,—,2–2,1–1,NaN,1–2,2–0,0–3,0–4,1–2,...,0–3,2–1,0–1,3–4,1–2,1–4,0–2,2–0,2–1,0–1
1,Athletico Paranaense,3–2,—,1–1,2–0,1–0,1–0,3–2,3–3,2–0,...,2–2,1–1,2–0,1–2,2–1,2–2,1–1,NaN,1–1,a
2,Atlético Mineiro,2–2,2–1,—,1–0,1–0,0–1,1–2,0–1,1–0,...,2–0,3–1,2–1,NaN,2–0,1–1,1–1,2–0,NaN,1–2
3,Bahia,3–1,1–1,NaN,—,1–2,0–0,3–1,2–2,0–3,...,1–0,2–0,1–1,1–2,1–0,1–0,4–0,1–2,NaN,1–1
4,Botafogo,2–0,1–1,2–0,3–0,—,3–0,4–1,NaN,0–1,...,1–0,2–0,1–1,3–4,3–1,3–4,2–0,a,2–1,2–0
5,Corinthians,1–1,1–0,1–1,a,1–0,—,3–1,2–1,1–1,...,2–0,1–1,1–1,4–4,a,0–0,0–1,1–1,1–1,3–1
6,Coritiba,3–1,2–0,1–2,2–4,NaN,NaN,—,1–0,0–3,...,2–0,0–3,0–1,1–2,0–1,0–2,0–1,0–0,1–1,0–0
7,Cruzeiro,1–1,NaN,0–1,3–0,0–0,1–1,0–0,—,0–1,...,0–2,0–1,0–1,1–0,1–2,a,0–0,2–1,1–0,a
8,Cuiabá,2–2,NaN,0–4,1–1,0–1,0–1,1–1,0–0,—,...,3–0,2–1,1–1,1–2,NaN,0–2,1–1,3–0,2–1,0–2
9,Flamengo,1–1,0–3,a,1–0,2–3,1–0,3–0,1–1,NaN,...,1–1,2–0,2–0,3–0,0–0,3–0,NaN,1–2,1–1,1–0
10,Fluminense,3–1,2–0,1–1,2–1,0–2,3–3,a,1–0,2–0,...,—,1–0,5–3,a,2–0,2–1,2–1,1–0,a,1–1
11,Fortaleza,3–2,1–0,2–1,0–0,NaN,2–1,3–1,0–1,0–1,...,4–2,—,NaN,1–1,1–1,NaN,0–3,4–0,0–0,2–0
12,Goiás,NaN,1–1,0–0,4–6,2–1,3–1,1–2,NaN,0–1,...,2–2,1–0,—,1–1,0–0,0–5,0–2,0–1,2–0,1–1
13,Grêmio,3–1,1–2,1–0,1–0,0–2,0–1,5–1,3–0,2–0,...,2–1,0–0,NaN,—,3–1,1–0,3–3,1–0,2–1,NaN
14,Internacional,1–1,0–2,0–2,2–0,NaN,2–2,3–4,0–0,1–2,...,0–0,0–1,1–0,3–2,—,0–0,NaN,7–1,2–1,2–1
15,Palmeiras,NaN,1–0,0–2,1–0,0–1,2–1,3–1,1–0,2–1,...,a,3–1,1–0,4–1,3–0,—,1–1,1–2,5–0,1–0
16,Red Bull Bragantino,2–2,2–0,1–2,2–1,2–2,1–0,NaN,0–3,2–0,...,1–0,NaN,2–0,2–0,0–0,2–1,—,2–0,0–0,1–1
17,Santos,3–2,1–1,0–0,3–0,2–2,0–2,2–1,0–3,0–0,...,a,NaN,4–3,2–1,1–1,0–0,1–3,—,0–0,4–1
18,São Paulo,3–0,2–1,0–2,0–0,0–0,2–1,2–1,1–0,NaN,...,1–0,1–2,2–1,3–0,2–0,0–2,1–0,4–1,—,4–2
19,Vasco da Gama,2–1,0–2,1–0,0–1,1–0,a,5–1,0–1,1–0,...,4–2,1–0,0–1,1–0,1–2,2–2,NaN,0–1,0–0,—

In [90]:
nomes_times = list(tabela_jogos["Casa \ Fora"])
apelidos = list(tabela_jogos.columns)
apelidos.pop(0)
print(nomes_times)
print(apelidos)

de_para_times = dict(zip(apelidos, nomes_times))
print(de_para_times)

['América Mineiro', 'Athletico Paranaense', 'Atlético Mineiro', 'Bahia', 'Botafogo', 'Corinthians', 'Coritiba', 'Cruzeiro', 'Cuiabá', 'Flamengo', 'Fluminense', 'Fortaleza', 'Goiás', 'Grêmio', 'Internacional', 'Palmeiras', 'Red Bull Bragantino', 'Santos', 'São Paulo', 'Vasco da Gama']
['AMM', 'ATP', 'ATM', 'BAH', 'BOT', 'COR', 'CTB', 'CRU', 'CUI', 'FLA', 'FLU', 'FOR', 'GOI', 'GRE', 'INT', 'PAL', 'RBB', 'SAN', 'SPA', 'VAS']
{'AMM': 'América Mineiro', 'ATP': 'Athletico Paranaense', 'ATM': 'Atlético Mineiro', 'BAH': 'Bahia', 'BOT': 'Botafogo', 'COR': 'Corinthians', 'CTB': 'Coritiba', 'CRU': 'Cruzeiro', 'CUI': 'Cuiabá', 'FLA': 'Flamengo', 'FLU': 'Fluminense', 'FOR': 'Fortaleza', 'GOI': 'Goiás', 'GRE': 'Grêmio', 'INT': 'Internacional', 'PAL': 'Palmeiras', 'RBB': 'Red Bull Bragantino', 'SAN': 'Santos', 'SPA': 'São Paulo', 'VAS': 'Vasco da Gama'}

In [91]:
tabela_jogos_ajustada = tabela_jogos.set_index("Casa \ Fora")
tabela_jogos_ajustada = tabela_jogos_ajustada.unstack().reset_index()
tabela_jogos_ajustada = tabela_jogos_ajustada.rename(columns={"level_0": "fora", "Casa \ Fora": "casa", 0: "resultado"})

def ajustar_apelido_time(linha):
    apelido = linha["fora"]
    nome = de_para_times[apelido]
    return nome

tabela_jogos_ajustada["fora"] = tabela_jogos_ajustada.apply(ajustar_apelido_time, axis=1)
tabela_jogos_ajustada = tabela_jogos_ajustada[tabela_jogos_ajustada["fora"]!=tabela_jogos_ajustada["casa"]]
display(tabela_jogos_ajustada)

                fora                  casa resultado
1    América Mineiro  Athletico Paranaense       3–2
2    América Mineiro      Atlético Mineiro       2–2
3    América Mineiro                 Bahia       3–1
4    América Mineiro              Botafogo       2–0
5    América Mineiro           Corinthians       1–1
..               ...                   ...       ...
394    Vasco da Gama         Internacional       2–1
395    Vasco da Gama             Palmeiras       1–0
396    Vasco da Gama   Red Bull Bragantino       1–1
397    Vasco da Gama                Santos       4–1
398    Vasco da Gama             São Paulo       4–2

[380 rows x 3 columns]

In [92]:
tabela_jogos_ajustada["resultado"] = tabela_jogos_ajustada["resultado"].fillna("a jogar")
tabela_jogos_realizados = tabela_jogos_ajustada[tabela_jogos_ajustada["resultado"].str.contains("–")]
display(tabela_jogos_realizados)
tabela_jogos_faltantes = tabela_jogos_ajustada[~tabela_jogos_ajustada["resultado"].str.contains("–")]
tabela_jogos_faltantes = tabela_jogos_faltantes.drop(columns=["resultado"])
display(tabela_jogos_faltantes)

                fora                  casa resultado
1    América Mineiro  Athletico Paranaense       3–2
2    América Mineiro      Atlético Mineiro       2–2
3    América Mineiro                 Bahia       3–1
4    América Mineiro              Botafogo       2–0
5    América Mineiro           Corinthians       1–1
..               ...                   ...       ...
394    Vasco da Gama         Internacional       2–1
395    Vasco da Gama             Palmeiras       1–0
396    Vasco da Gama   Red Bull Bragantino       1–1
397    Vasco da Gama                Santos       4–1
398    Vasco da Gama             São Paulo       4–2

[336 rows x 3 columns]

                     fora                  casa
12        América Mineiro                 Goiás
15        América Mineiro             Palmeiras
27   Athletico Paranaense              Cruzeiro
28   Athletico Paranaense                Cuiabá
43       Atlético Mineiro                 Bahia
49       Atlético Mineiro              Flamengo
60                  Bahia       América Mineiro
65                  Bahia           Corinthians
86               Botafogo              Coritiba
91               Botafogo             Fortaleza
94               Botafogo         Internacional
106           Corinthians              Coritiba
119           Corinthians         Vasco da Gama
130              Coritiba            Fluminense
136              Coritiba   Red Bull Bragantino
144              Cruzeiro              Botafogo
152              Cruzeiro                 Goiás
169                Cuiabá              Flamengo
178                Cuiabá             São Paulo
180              Flamengo       América Mineiro
198              Flamengo             São Paulo
215            Fluminense             Palmeiras
217            Fluminense                Santos
236             Fortaleza   Red Bull Bragantino
237             Fortaleza                Santos
251                 Goiás             Fortaleza
253                 Goiás                Grêmio
262                Grêmio      Atlético Mineiro
270                Grêmio            Fluminense
285         Internacional           Corinthians
288         Internacional                Cuiabá
307             Palmeiras              Cruzeiro
311             Palmeiras             Fortaleza
329   Red Bull Bragantino              Flamengo
334   Red Bull Bragantino         Internacional
339   Red Bull Bragantino         Vasco da Gama
341                Santos  Athletico Paranaense
344                Santos              Botafogo
362             São Paulo      Atlético Mineiro
363             São Paulo                 Bahia
370             São Paulo            Fluminense
381         Vasco da Gama  Athletico Paranaense
387         Vasco da Gama              Cruzeiro
393         Vasco da Gama                Grêmio

In [93]:


tabela_jogos_realizados[["gols_casa", "gols_fora"]] = tabela_jogos_realizados["resultado"].str.split("–", expand=True)
tabela_jogos_realizados = tabela_jogos_realizados.drop(columns=["resultado"])
tabela_jogos_realizados["gols_casa"] = tabela_jogos_realizados["gols_casa"].astype(int)
tabela_jogos_realizados["gols_fora"] = tabela_jogos_realizados["gols_fora"].astype(int)
display(tabela_jogos_realizados)

C:\Users\joaol\AppData\Local\Temp\ipykernel_13472\3699354807.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_jogos_realizados[["gols_casa", "gols_fora"]] = tabela_jogos_realizados["resultado"].str.split("–", expand=True)
C:\Users\joaol\AppData\Local\Temp\ipykernel_13472\3699354807.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_jogos_realizados[["gols_casa", "gols_fora"]] = tabela_jogos_realizados["resultado"].str.split("–", expand=True)

                fora                  casa  gols_casa  gols_fora
1    América Mineiro  Athletico Paranaense          3          2
2    América Mineiro      Atlético Mineiro          2          2
3    América Mineiro                 Bahia          3          1
4    América Mineiro              Botafogo          2          0
5    América Mineiro           Corinthians          1          1
..               ...                   ...        ...        ...
394    Vasco da Gama         Internacional          2          1
395    Vasco da Gama             Palmeiras          1          0
396    Vasco da Gama   Red Bull Bragantino          1          1
397    Vasco da Gama                Santos          4          1
398    Vasco da Gama             São Paulo          4          2

[336 rows x 4 columns]

In [94]:
# media gols feitos dentro de casa
# media gols feitos fora de casa
# media gols sofridos dentro de casa
# media gols sofridos fora de casa

media_gols_casa = tabela_jogos_realizados.groupby("casa").mean(numeric_only=True)
media_gols_casa = media_gols_casa.rename(columns={"gols_casa": "gols_feitos_casa", "gols_fora": "gols_sofridos_casa"})
display(media_gols_casa)
media_gols_fora = tabela_jogos_realizados.groupby("fora").mean(numeric_only=True)
media_gols_fora = media_gols_fora.rename(columns={"gols_casa": "gols_sofridos_fora", "gols_fora": "gols_feitos_fora"})
display(media_gols_fora)

                      gols_feitos_casa  gols_sofridos_casa
casa
América Mineiro               1.058824            1.941176
Athletico Paranaense          1.764706            1.117647
Atlético Mineiro              1.352941            0.882353
Bahia                         1.470588            1.117647
Botafogo                      2.058824            0.941176
Corinthians                   1.411765            0.941176
Coritiba                      0.882353            1.411765
Cruzeiro                      0.625000            0.812500
Cuiabá                        1.176471            1.176471
Flamengo                      1.437500            0.750000
Fluminense                    1.750000            0.875000
Fortaleza                     1.437500            1.000000
Goiás                         1.058824            1.411765
Grêmio                        1.823529            0.882353
Internacional                 1.529412            1.176471
Palmeiras                     1.764706            0.705882
Red Bull Bragantino           1.529412            0.705882
Santos                        1.470588            1.352941
São Paulo                     1.647059            0.764706
Vasco da Gama                 1.176471            1.058824

                      gols_sofridos_fora  gols_feitos_fora
fora
América Mineiro                 2.235294          1.235294
Athletico Paranaense            1.176471          1.000000
Atlético Mineiro                0.705882          1.176471
Bahia                           1.647059          0.823529
Botafogo                        0.875000          1.125000
Corinthians                     1.352941          0.882353
Coritiba                        2.470588          1.352941
Cruzeiro                        0.882353          1.176471
Cuiabá                          0.882353          0.941176
Flamengo                        1.470588          1.588235
Fluminense                      1.647059          0.882353
Fortaleza                       1.294118          0.764706
Goiás                           1.470588          0.941176
Grêmio                          2.058824          1.529412
Internacional                   1.352941          0.705882
Palmeiras                       1.058824          1.529412
Red Bull Bragantino             1.062500          1.250000
Santos                          1.882353          0.705882
São Paulo                       1.375000          0.562500
Vasco da Gama                   1.500000          0.875000

In [95]:
tabela_estatisticas = media_gols_casa.merge(media_gols_fora, left_index=True, right_index=True)
tabela_estatisticas = tabela_estatisticas.reset_index()
tabela_estatisticas = tabela_estatisticas.rename(columns={"casa": "time"})
display(tabela_estatisticas)

,time,gols_feitos_casa,gols_sofridos_casa,gols_sofridos_fora,gols_feitos_fora
0,América Mineiro,1.058824,1.941176,2.235294,1.235294
1,Athletico Paranaense,1.764706,1.117647,1.176471,1.000000
2,Atlético Mineiro,1.352941,0.882353,0.705882,1.176471
3,Bahia,1.470588,1.117647,1.647059,0.823529
4,Botafogo,2.058824,0.941176,0.875000,1.125000
5,Corinthians,1.411765,0.941176,1.352941,0.882353
6,Coritiba,0.882353,1.411765,2.470588,1.352941
7,Cruzeiro,0.625000,0.812500,0.882353,1.176471
8,Cuiabá,1.176471,1.176471,0.882353,0.941176
9,Flamengo,1.437500,0.750000,1.470588,1.588235
10,Fluminense,1.750000,0.875000,1.647059,0.882353
11,Fortaleza,1.437500,1.000000,1.294118,0.764706
12,Goiás,1.058824,1.411765,1.470588,0.941176
13,Grêmio,1.823529,0.882353,2.058824,1.529412
14,Internacional,1.529412,1.176471,1.352941,0.705882
15,Palmeiras,1.764706,0.705882,1.058824,1.529412
16,Red Bull Bragantino,1.529412,0.705882,1.062500,1.250000
17,Santos,1.470588,1.352941,1.882353,0.705882
18,São Paulo,1.647059,0.764706,1.375000,0.562500
19,Vasco da Gama,1.176471,1.058824,1.500000,0.875000

In [96]:
from scipy.stats import poisson

# como a partir das medias calcular a probabilidade do time ganhar/perder/empate

def calcular_pontuacao_esperada(linha):
    time_casa = linha["casa"]
    time_fora = linha["fora"]

    # qual a média de gols que o Cruzeiro, jogando em casa, faz contra o Vasco, jogando fora de casa
    lambda_casa = (tabela_estatisticas.loc[tabela_estatisticas["time"]==time_casa, "gols_feitos_casa"].iloc[0] 
                * tabela_estatisticas.loc[tabela_estatisticas["time"]==time_fora, "gols_sofridos_fora"].iloc[0])
    # média de gols cruzeiro dentro de casa * média de gols sofridos pelo vasco fora de casa


    # média de gols que o vasco faz fora de casa * media de gols que o Cruzeiro sofre dentro de casa
    lambda_fora =  (tabela_estatisticas.loc[tabela_estatisticas["time"]==time_fora, "gols_feitos_fora"].iloc[0] 
                    * tabela_estatisticas.loc[tabela_estatisticas["time"]==time_casa, "gols_sofridos_casa"].iloc[0])




    pv_casa = 0
    p_empate = 0
    pv_fora = 0

    for gols_casa in range(8):
        for gols_fora in range(8):
            probabilidade_resultado = poisson.pmf(gols_casa, lambda_casa) * poisson.pmf(gols_fora, lambda_fora)
            if gols_casa == gols_fora:
                p_empate += probabilidade_resultado
            elif gols_casa > gols_fora:
                pv_casa += probabilidade_resultado
            elif gols_casa < gols_fora:
                pv_fora += probabilidade_resultado

    # print(pv_casa)
    # print(p_empate)
    # print(pv_fora)

    ve_casa = pv_casa * 3 + p_empate
    ve_fora = pv_fora * 3 + p_empate
    linha["pontos_casa"] = ve_casa
    linha["pontos_fora"] = ve_fora
    return linha

# como a partir da probabilidade você calcula a pontuação que o time vai ter
# ValorEsperado - pontuação do vasco

# Vasco x Cruzeiro

# p_vasco = 50% * 3 + 10% * 1
# p_cruzeiro = 40% * 3 + 10% * 1

# 50% * 3 = 1.8
# 10%
# 40% * 3 = 1.2

In [97]:
tabela_jogos_faltantes = tabela_jogos_faltantes.apply(calcular_pontuacao_esperada, axis=1)
display(tabela_jogos_faltantes)

                     fora                  casa  pontos_casa  pontos_fora
12        América Mineiro                 Goiás     1.744481     1.049207
15        América Mineiro             Palmeiras     2.595239     0.189743
27   Athletico Paranaense              Cruzeiro     1.252852     1.387050
28   Athletico Paranaense                Cuiabá     1.514050     1.221000
43       Atlético Mineiro                 Bahia     1.159271     1.563992
49       Atlético Mineiro              Flamengo     1.447352     1.235058
60                  Bahia       América Mineiro     1.475874     1.293978
65                  Bahia           Corinthians     2.326984     0.493741
86               Botafogo              Coritiba     0.794007     1.954401
91               Botafogo             Fortaleza     1.458196     1.264551
94               Botafogo         Internacional     1.379835     1.359392
106           Corinthians              Coritiba     1.325465     1.400426
119           Corinthians         Vasco da Gama     1.832944     0.915119
130              Coritiba            Fluminense     2.486301     0.222828
136              Coritiba   Red Bull Bragantino     2.561852     0.237396
144              Cruzeiro              Botafogo     1.847315     0.920898
152              Cruzeiro                 Goiás     0.878222     1.876844
169                Cuiabá              Flamengo     1.790275     0.915610
178                Cuiabá             São Paulo     1.908563     0.823122
180              Flamengo       América Mineiro     0.651753     2.154017
198              Flamengo             São Paulo     2.092654     0.713349
215            Fluminense             Palmeiras     2.588109     0.270013
217            Fluminense                Santos     2.105466     0.701259
236             Fortaleza   Red Bull Bragantino     2.339365     0.465070
237             Fortaleza                Santos     1.948382     0.827771
251                 Goiás             Fortaleza     2.123948     0.672203
253                 Goiás                Grêmio     2.420174     0.416899
262                Grêmio      Atlético Mineiro     2.162759     0.650528
270                Grêmio            Fluminense     2.387441     0.406014
285         Internacional           Corinthians     2.216727     0.572555
288         Internacional                Cuiabá     1.911553     0.836720
307             Palmeiras              Cruzeiro     0.892741     1.808154
311             Palmeiras             Fortaleza     1.374297     1.383907
329   Red Bull Bragantino              Flamengo     1.788339     0.953132
334   Red Bull Bragantino         Internacional     1.480514     1.280220
339   Red Bull Bragantino         Vasco da Gama     1.315313     1.419041
341                Santos  Athletico Paranaense     2.583874     0.257519
344                Santos              Botafogo     2.662062     0.143935
362             São Paulo      Atlético Mineiro     2.316384     0.476934
363             São Paulo                 Bahia     2.295660     0.507581
370             São Paulo            Fluminense     2.530738     0.316649
381         Vasco da Gama  Athletico Paranaense     2.324640     0.502164
387         Vasco da Gama              Cruzeiro     1.519955     1.136459
393         Vasco da Gama                Grêmio     2.468519     0.374422

In [98]:
def ajustar_nome_time(linha):
    for nome in nomes_times:
        if nome in linha["Equipevde"]:
            return nome
    
tabela_classificacao["time"] = tabela_classificacao.apply(ajustar_nome_time, axis=1)
tabela_classificacao_atualizada = tabela_classificacao[["time", "Pts"]]
tabela_classificacao_atualizada["Pts"] = tabela_classificacao_atualizada["Pts"].astype(int)

display(tabela_classificacao_atualizada)

C:\Users\joaol\AppData\Local\Temp\ipykernel_13472\2564768963.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_classificacao_atualizada["Pts"] = tabela_classificacao_atualizada["Pts"].astype(int)

                    time  Pts
0              Palmeiras   62
1               Botafogo   60
2                 Grêmio   59
3    Red Bull Bragantino   59
4       Atlético Mineiro   57
5               Flamengo   57
6   Athletico Paranaense   51
7             Fluminense   47
8                 Cuiabá   47
9              São Paulo   46
10           Corinthians   44
11             Fortaleza   43
12         Internacional   43
13                Santos   42
14         Vasco da Gama   40
15              Cruzeiro   40
16                 Bahia   38
17                 Goiás   35
18              Coritiba   29
19       América Mineiro   21

In [99]:
tabela_pontuacao_casa = tabela_jogos_faltantes.groupby("casa").sum(numeric_only=True)[["pontos_casa"]]
tabela_pontuacao_fora = tabela_jogos_faltantes.groupby("fora").sum(numeric_only=True)[["pontos_fora"]]
display(tabela_pontuacao_casa)
display(tabela_pontuacao_fora)

                      pontos_casa
casa
América Mineiro          2.127627
Athletico Paranaense     4.908514
Atlético Mineiro         4.479143
Bahia                    3.454930
Botafogo                 4.509377
Corinthians              4.543711
Coritiba                 2.119472
Cruzeiro                 3.665548
Cuiabá                   3.425603
Flamengo                 5.025966
Fluminense               7.404480
Fortaleza                4.956441
Goiás                    2.622703
Grêmio                   4.888693
Internacional            2.860349
Palmeiras                5.183348
Red Bull Bragantino      4.901217
Santos                   4.053847
São Paulo                4.001217
Vasco da Gama            3.148257

                      pontos_fora
fora
América Mineiro          1.238950
Athletico Paranaense     2.608050
Atlético Mineiro         2.799050
Bahia                    1.787719
Botafogo                 4.578344
Corinthians              2.315545
Coritiba                 0.460224
Cruzeiro                 2.797742
Cuiabá                   1.738732
Flamengo                 2.867366
Fluminense               0.971272
Fortaleza                1.292841
Goiás                    1.089103
Grêmio                   1.056542
Internacional            1.409276
Palmeiras                3.192061
Red Bull Bragantino      3.652393
Santos                   0.401454
São Paulo                1.301164
Vasco da Gama            2.013045

In [100]:
def atualizar_pontuacao_previsao(linha):
    time = linha["time"]
    pontuacao = int(linha["Pts"]) + float(tabela_pontuacao_casa.loc[time, "pontos_casa"]) + float(tabela_pontuacao_fora.loc[time, "pontos_fora"])
    return pontuacao


tabela_classificacao_atualizada["Pts"] = tabela_classificacao_atualizada.apply(atualizar_pontuacao_previsao, axis=1)
tabela_classificacao_atualizada = tabela_classificacao_atualizada.sort_values(by="Pts", ascending=False)
tabela_classificacao_atualizada = tabela_classificacao_atualizada.reset_index(drop=True)
tabela_classificacao_atualizada.index = tabela_classificacao_atualizada.index + 1
display(tabela_classificacao_atualizada)

C:\Users\joaol\AppData\Local\Temp\ipykernel_13472\3357124533.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_classificacao_atualizada["Pts"] = tabela_classificacao_atualizada.apply(atualizar_pontuacao_previsao, axis=1)

                    time        Pts
1              Palmeiras  70.375409
2               Botafogo  69.087721
3    Red Bull Bragantino  67.553610
4                 Grêmio  64.945235
5               Flamengo  64.893332
6       Atlético Mineiro  64.278193
7   Athletico Paranaense  58.516563
8             Fluminense  55.375752
9                 Cuiabá  52.164335
10             São Paulo  51.302381
11           Corinthians  50.859256
12             Fortaleza  49.249282
13         Internacional  47.269625
14              Cruzeiro  46.463289
15                Santos  46.455301
16         Vasco da Gama  45.161302
17                 Bahia  43.242649
18                 Goiás  38.711806
19              Coritiba  31.579696
20       América Mineiro  24.366577